/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.records.Keys;
import org.jooq.records.Public;
import org.jooq.records.tables.Treatments.TreatmentsPath;
import org.jooq.records.tables.records.TestamentsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Testaments extends TableImpl<TestamentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.testaments</code>
     */
    public static final Testaments TESTAMENTS = new Testaments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestamentsRecord> getRecordType() {
        return TestamentsRecord.class;
    }

    /**
     * The column <code>public.testaments.testamentid</code>.
     */
    public final TableField<TestamentsRecord, Integer> TESTAMENTID = createField(DSL.name("testamentid"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>public.testaments.treatmentdescription</code>.
     */
    public final TableField<TestamentsRecord, String> TREATMENTDESCRIPTION = createField(DSL.name("treatmentdescription"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.testaments.customername</code>.
     */
    public final TableField<TestamentsRecord, String> CUSTOMERNAME = createField(DSL.name("customername"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.testaments.treatmentid</code>.
     */
    public final TableField<TestamentsRecord, Integer> TREATMENTID = createField(DSL.name("treatmentid"), SQLDataType.INTEGER.nullable(false), this, "");

    private Testaments(Name alias, Table<TestamentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Testaments(Name alias, Table<TestamentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.testaments</code> table reference
     */
    public Testaments(String alias) {
        this(DSL.name(alias), TESTAMENTS);
    }

    /**
     * Create an aliased <code>public.testaments</code> table reference
     */
    public Testaments(Name alias) {
        this(alias, TESTAMENTS);
    }

    /**
     * Create a <code>public.testaments</code> table reference
     */
    public Testaments() {
        this(DSL.name("testaments"), null);
    }

    public <O extends Record> Testaments(Table<O> path, ForeignKey<O, TestamentsRecord> childPath, InverseForeignKey<O, TestamentsRecord> parentPath) {
        super(path, childPath, parentPath, TESTAMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TestamentsPath extends Testaments implements Path<TestamentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TestamentsPath(Table<O> path, ForeignKey<O, TestamentsRecord> childPath, InverseForeignKey<O, TestamentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TestamentsPath(Name alias, Table<TestamentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TestamentsPath as(String alias) {
            return new TestamentsPath(DSL.name(alias), this);
        }

        @Override
        public TestamentsPath as(Name alias) {
            return new TestamentsPath(alias, this);
        }

        @Override
        public TestamentsPath as(Table<?> alias) {
            return new TestamentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TestamentsRecord, Integer> getIdentity() {
        return (Identity<TestamentsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TestamentsRecord> getPrimaryKey() {
        return Keys.TESTAMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<TestamentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TESTAMENTS__FK_TESTAMENT_TREATMENT);
    }

    private transient TreatmentsPath _treatments;

    /**
     * Get the implicit join path to the <code>public.treatments</code> table.
     */
    public TreatmentsPath treatments() {
        if (_treatments == null)
            _treatments = new TreatmentsPath(this, Keys.TESTAMENTS__FK_TESTAMENT_TREATMENT, null);

        return _treatments;
    }

    @Override
    public Testaments as(String alias) {
        return new Testaments(DSL.name(alias), this);
    }

    @Override
    public Testaments as(Name alias) {
        return new Testaments(alias, this);
    }

    @Override
    public Testaments as(Table<?> alias) {
        return new Testaments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Testaments rename(String name) {
        return new Testaments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Testaments rename(Name name) {
        return new Testaments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Testaments rename(Table<?> name) {
        return new Testaments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Testaments where(Condition condition) {
        return new Testaments(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Testaments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Testaments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Testaments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Testaments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Testaments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Testaments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Testaments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Testaments whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Testaments whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
