/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables;


import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.records.Keys;
import org.jooq.records.Public;
import org.jooq.records.tables.records.TitleImageRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TitleImage extends TableImpl<TitleImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.title_image</code>
     */
    public static final TitleImage TITLE_IMAGE = new TitleImage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TitleImageRecord> getRecordType() {
        return TitleImageRecord.class;
    }

    /**
     * The column <code>public.title_image.imageid</code>.
     */
    public final TableField<TitleImageRecord, Integer> IMAGEID = createField(DSL.name("imageid"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>public.title_image.imagename</code>.
     */
    public final TableField<TitleImageRecord, String> IMAGENAME = createField(DSL.name("imagename"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.title_image.date</code>.
     */
    public final TableField<TitleImageRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private TitleImage(Name alias, Table<TitleImageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TitleImage(Name alias, Table<TitleImageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.title_image</code> table reference
     */
    public TitleImage(String alias) {
        this(DSL.name(alias), TITLE_IMAGE);
    }

    /**
     * Create an aliased <code>public.title_image</code> table reference
     */
    public TitleImage(Name alias) {
        this(alias, TITLE_IMAGE);
    }

    /**
     * Create a <code>public.title_image</code> table reference
     */
    public TitleImage() {
        this(DSL.name("title_image"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TitleImageRecord, Integer> getIdentity() {
        return (Identity<TitleImageRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TitleImageRecord> getPrimaryKey() {
        return Keys.TITLE_IMAGE_PKEY;
    }

    @Override
    public TitleImage as(String alias) {
        return new TitleImage(DSL.name(alias), this);
    }

    @Override
    public TitleImage as(Name alias) {
        return new TitleImage(alias, this);
    }

    @Override
    public TitleImage as(Table<?> alias) {
        return new TitleImage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TitleImage rename(String name) {
        return new TitleImage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TitleImage rename(Name name) {
        return new TitleImage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TitleImage rename(Table<?> name) {
        return new TitleImage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TitleImage where(Condition condition) {
        return new TitleImage(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TitleImage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TitleImage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TitleImage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TitleImage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TitleImage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TitleImage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TitleImage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TitleImage whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TitleImage whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
