/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables;


import java.time.LocalDate;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.records.Public;
import org.jooq.records.tables.records.TitleRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Title extends TableImpl<TitleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.title</code>
     */
    public static final Title TITLE = new Title();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TitleRecord> getRecordType() {
        return TitleRecord.class;
    }

    /**
     * The column <code>public.title.titleid</code>.
     */
    public final TableField<TitleRecord, UUID> TITLEID = createField(DSL.name("titleid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.title.description</code>.
     */
    public final TableField<TitleRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.title.imageid</code>.
     */
    public final TableField<TitleRecord, Integer> IMAGEID = createField(DSL.name("imageid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.title.imagename</code>.
     */
    public final TableField<TitleRecord, String> IMAGENAME = createField(DSL.name("imagename"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.title.date</code>.
     */
    public final TableField<TitleRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private Title(Name alias, Table<TitleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Title(Name alias, Table<TitleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.title</code> table reference
     */
    public Title(String alias) {
        this(DSL.name(alias), TITLE);
    }

    /**
     * Create an aliased <code>public.title</code> table reference
     */
    public Title(Name alias) {
        this(alias, TITLE);
    }

    /**
     * Create a <code>public.title</code> table reference
     */
    public Title() {
        this(DSL.name("title"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Title as(String alias) {
        return new Title(DSL.name(alias), this);
    }

    @Override
    public Title as(Name alias) {
        return new Title(alias, this);
    }

    @Override
    public Title as(Table<?> alias) {
        return new Title(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Title rename(String name) {
        return new Title(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Title rename(Name name) {
        return new Title(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Title rename(Table<?> name) {
        return new Title(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Title where(Condition condition) {
        return new Title(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Title where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Title where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Title where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Title where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Title where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Title where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Title where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Title whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Title whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
