/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.records.Keys;
import org.jooq.records.Public;
import org.jooq.records.tables.Testaments.TestamentsPath;
import org.jooq.records.tables.records.TreatmentsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Treatments extends TableImpl<TreatmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.treatments</code>
     */
    public static final Treatments TREATMENTS = new Treatments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TreatmentsRecord> getRecordType() {
        return TreatmentsRecord.class;
    }

    /**
     * The column <code>public.treatments.treatmentid</code>.
     */
    public final TableField<TreatmentsRecord, Integer> TREATMENTID = createField(DSL.name("treatmentid"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>public.treatments.treatmentname</code>.
     */
    public final TableField<TreatmentsRecord, String> TREATMENTNAME = createField(DSL.name("treatmentname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.treatments.treatmentdescription</code>.
     */
    public final TableField<TreatmentsRecord, String> TREATMENTDESCRIPTION = createField(DSL.name("treatmentdescription"), SQLDataType.CLOB.nullable(false), this, "");

    private Treatments(Name alias, Table<TreatmentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Treatments(Name alias, Table<TreatmentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.treatments</code> table reference
     */
    public Treatments(String alias) {
        this(DSL.name(alias), TREATMENTS);
    }

    /**
     * Create an aliased <code>public.treatments</code> table reference
     */
    public Treatments(Name alias) {
        this(alias, TREATMENTS);
    }

    /**
     * Create a <code>public.treatments</code> table reference
     */
    public Treatments() {
        this(DSL.name("treatments"), null);
    }

    public <O extends Record> Treatments(Table<O> path, ForeignKey<O, TreatmentsRecord> childPath, InverseForeignKey<O, TreatmentsRecord> parentPath) {
        super(path, childPath, parentPath, TREATMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TreatmentsPath extends Treatments implements Path<TreatmentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TreatmentsPath(Table<O> path, ForeignKey<O, TreatmentsRecord> childPath, InverseForeignKey<O, TreatmentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TreatmentsPath(Name alias, Table<TreatmentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TreatmentsPath as(String alias) {
            return new TreatmentsPath(DSL.name(alias), this);
        }

        @Override
        public TreatmentsPath as(Name alias) {
            return new TreatmentsPath(alias, this);
        }

        @Override
        public TreatmentsPath as(Table<?> alias) {
            return new TreatmentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TreatmentsRecord, Integer> getIdentity() {
        return (Identity<TreatmentsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TreatmentsRecord> getPrimaryKey() {
        return Keys.TREATMENTS_PKEY;
    }

    private transient TestamentsPath _testaments;

    /**
     * Get the implicit to-many join path to the <code>public.testaments</code>
     * table
     */
    public TestamentsPath testaments() {
        if (_testaments == null)
            _testaments = new TestamentsPath(this, null, Keys.TESTAMENTS__FK_TESTAMENT_TREATMENT.getInverseKey());

        return _testaments;
    }

    @Override
    public Treatments as(String alias) {
        return new Treatments(DSL.name(alias), this);
    }

    @Override
    public Treatments as(Name alias) {
        return new Treatments(alias, this);
    }

    @Override
    public Treatments as(Table<?> alias) {
        return new Treatments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Treatments rename(String name) {
        return new Treatments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Treatments rename(Name name) {
        return new Treatments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Treatments rename(Table<?> name) {
        return new Treatments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Treatments where(Condition condition) {
        return new Treatments(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Treatments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Treatments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Treatments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Treatments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Treatments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Treatments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Treatments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Treatments whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Treatments whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
