/*
 * This file is generated by jOOQ.
 */
package org.jooq.records;


import org.jooq.records.tables.FlywaySchemaHistory;
import org.jooq.records.tables.Title;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.title</code>.
     */
    public static final Title TITLE = Title.TITLE;
}
