/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.records.tables.Testaments;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestamentsRecord extends UpdatableRecordImpl<TestamentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.testaments.testamentid</code>.
     */
    public void setTestamentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.testaments.testamentid</code>.
     */
    public Integer getTestamentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.testaments.treatmentdescription</code>.
     */
    public void setTreatmentdescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.testaments.treatmentdescription</code>.
     */
    public String getTreatmentdescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.testaments.customername</code>.
     */
    public void setCustomername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.testaments.customername</code>.
     */
    public String getCustomername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.testaments.treatmentid</code>.
     */
    public void setTreatmentid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.testaments.treatmentid</code>.
     */
    public Integer getTreatmentid() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestamentsRecord
     */
    public TestamentsRecord() {
        super(Testaments.TESTAMENTS);
    }

    /**
     * Create a detached, initialised TestamentsRecord
     */
    public TestamentsRecord(Integer testamentid, String treatmentdescription, String customername, Integer treatmentid) {
        super(Testaments.TESTAMENTS);

        setTestamentid(testamentid);
        setTreatmentdescription(treatmentdescription);
        setCustomername(customername);
        setTreatmentid(treatmentid);
        resetTouchedOnNotNull();
    }
}
