/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.records.tables.TitleImage;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TitleImageRecord extends UpdatableRecordImpl<TitleImageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.title_image.imageid</code>.
     */
    public void setImageid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.title_image.imageid</code>.
     */
    public Integer getImageid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.title_image.imagename</code>.
     */
    public void setImagename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.title_image.imagename</code>.
     */
    public String getImagename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.title_image.date</code>.
     */
    public void setDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.title_image.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TitleImageRecord
     */
    public TitleImageRecord() {
        super(TitleImage.TITLE_IMAGE);
    }

    /**
     * Create a detached, initialised TitleImageRecord
     */
    public TitleImageRecord(Integer imageid, String imagename, LocalDate date) {
        super(TitleImage.TITLE_IMAGE);

        setImageid(imageid);
        setImagename(imagename);
        setDate(date);
        resetTouchedOnNotNull();
    }
}
