/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables.records;


import java.time.LocalDate;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;
import org.jooq.records.tables.Title;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TitleRecord extends TableRecordImpl<TitleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.title.titleid</code>.
     */
    public void setTitleid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.title.titleid</code>.
     */
    public UUID getTitleid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.title.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.title.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.title.imageid</code>.
     */
    public void setImageid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.title.imageid</code>.
     */
    public Integer getImageid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.title.imagename</code>.
     */
    public void setImagename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.title.imagename</code>.
     */
    public String getImagename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.title.date</code>.
     */
    public void setDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.title.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TitleRecord
     */
    public TitleRecord() {
        super(Title.TITLE);
    }

    /**
     * Create a detached, initialised TitleRecord
     */
    public TitleRecord(UUID titleid, String description, Integer imageid, String imagename, LocalDate date) {
        super(Title.TITLE);

        setTitleid(titleid);
        setDescription(description);
        setImageid(imageid);
        setImagename(imagename);
        setDate(date);
        resetTouchedOnNotNull();
    }
}
