/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.records.tables.Title;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TitleRecord extends UpdatableRecordImpl<TitleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.title.description</code>.
     */
    public void setDescription(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.title.description</code>.
     */
    public String getDescription() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.title.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.title.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.title.titleid</code>.
     */
    public void setTitleid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.title.titleid</code>.
     */
    public Integer getTitleid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TitleRecord
     */
    public TitleRecord() {
        super(Title.TITLE);
    }

    /**
     * Create a detached, initialised TitleRecord
     */
    public TitleRecord(String description, LocalDate date, Integer titleid) {
        super(Title.TITLE);

        setDescription(description);
        setDate(date);
        setTitleid(titleid);
        resetTouchedOnNotNull();
    }
}
