/*
 * This file is generated by jOOQ.
 */
package org.jooq.records.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.records.tables.Treatments;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TreatmentsRecord extends UpdatableRecordImpl<TreatmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.treatments.treatmentid</code>.
     */
    public void setTreatmentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treatments.treatmentid</code>.
     */
    public Integer getTreatmentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.treatments.treatmentname</code>.
     */
    public void setTreatmentname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treatments.treatmentname</code>.
     */
    public String getTreatmentname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.treatments.treatmentdescription</code>.
     */
    public void setTreatmentdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.treatments.treatmentdescription</code>.
     */
    public String getTreatmentdescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreatmentsRecord
     */
    public TreatmentsRecord() {
        super(Treatments.TREATMENTS);
    }

    /**
     * Create a detached, initialised TreatmentsRecord
     */
    public TreatmentsRecord(Integer treatmentid, String treatmentname, String treatmentdescription) {
        super(Treatments.TREATMENTS);

        setTreatmentid(treatmentid);
        setTreatmentname(treatmentname);
        setTreatmentdescription(treatmentdescription);
        resetTouchedOnNotNull();
    }
}
